on:
  push:

name: Cargo-test

jobs:
  unix:
    name: Unix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain (windows)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - name: Setup (windows)
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Cargo test
        run: |
          cross test --target x86_64-pc-windows-gnu
